### ISSUE TITLE
I need to contact you

### ISSUE THREAD

**Issue by Yoticc** [coolmann24/BedrockFinderCpp#17]
Hi, I need help upgrade the bedrock finder for Nether 1.12 and versions over 1.15.
Could you give me your contacts so I can contact you in the future.

When you sebt, close the issue - unless of course it's more convenient for you to communicate here.

Thanks in advance.

**Comment by Boobies** [comment]
Also give him your personal phone number and a place in your bed so you can feel his warm, gentle breathing on the back of your neck as you fall asleep. He's too shy so he toned it down a bit to not seem too eager.
